/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.InterfaceMagnament.UserInterfaceMagnament;
import Models.TokenMagnament.TokenBag;
import Models.enums.TokenTypes;
import javax.swing.JFrame;

/**
 *
 * @author sirbon
 */
public class GraphicsViewer extends javax.swing.JDialog {

    private final UserInterfaceMagnament userInterfaceMagnament;
    private final TokenBag tokenBag;

    /**
     * Creates new form GraphicsViewer
     *
     * @param userInterfaceMagnament
     * @param tokenBag
     * @param parentFrame
     */
    public GraphicsViewer(UserInterfaceMagnament userInterfaceMagnament, TokenBag tokenBag, JFrame parentFrame) {

        this.tokenBag = tokenBag;
        this.userInterfaceMagnament = userInterfaceMagnament;
        initComponents();
        setLocationRelativeTo(null);
        fillPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicPanel = new javax.swing.JPanel();
        toGraphLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        identifiersPane = new javax.swing.JPanel();
        rsrvdWordsPane = new javax.swing.JPanel();
        integersPane = new javax.swing.JPanel();
        decimalPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        graphicPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toGraphLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toGraphLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        identifiersPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.IDNT_TKN.ordinal())
            , 0));
    jTabbedPane1.addTab("Identifiers", identifiersPane);

    rsrvdWordsPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.RSRVDWRD_TKN.ordinal())
        , 0));
jTabbedPane1.addTab("Reserved Words", rsrvdWordsPane);

integersPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.INT_TKN.ordinal())
    , 0));
    jTabbedPane1.addTab("Integers", integersPane);

    decimalPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.DEC_TKN.ordinal())
        , 0));
jTabbedPane1.addTab("Decimals", decimalPane);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillPanels() {
        userInterfaceMagnament.setToGraphPanel(graphicPanel);
        userInterfaceMagnament.setToGrphLabel(toGraphLabel);
        userInterfaceMagnament.setJdialogParent(this);
        
        userInterfaceMagnament.tokenStacker(identifiersPane, tokenBag.groupTokens(TokenTypes.IDNT_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(integersPane, tokenBag.groupTokens(TokenTypes.INT_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(decimalPane, tokenBag.groupTokens(TokenTypes.DEC_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(rsrvdWordsPane, tokenBag.groupTokens(TokenTypes.RSRVDWRD_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel decimalPane;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JPanel identifiersPane;
    private javax.swing.JPanel integersPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel rsrvdWordsPane;
    private javax.swing.JLabel toGraphLabel;
    // End of variables declaration//GEN-END:variables
}
