/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.InterfaceMagnament.UserInterfaceMagnament;
import Lexic.TokenMagnament.TokenBag;
import Enums.TokenTypes;
import javax.swing.JFrame;

/**
 *
 * @author sirbon
 */
public class GraphicsViewer extends javax.swing.JDialog {

    private final UserInterfaceMagnament userInterfaceMagnament;
    private final TokenBag tokenBag;

    /**
     * Creates new form GraphicsViewer
     *
     * @param userInterfaceMagnament
     * @param tokenBag
     * @param parentFrame
     */
    public GraphicsViewer(UserInterfaceMagnament userInterfaceMagnament, TokenBag tokenBag, JFrame parentFrame) {

        this.tokenBag = tokenBag;
        this.userInterfaceMagnament = userInterfaceMagnament;
        initComponents();
        setLocationRelativeTo(null);
        fillPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicPanel = new javax.swing.JScrollPane();
        toGraphLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        identifiersPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        decimalPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        integersPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rsrvdWordsPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(153, 153, 153));

        graphicPanel.setBackground(new java.awt.Color(153, 153, 153));
        graphicPanel.setForeground(new java.awt.Color(255, 255, 204));

        toGraphLabel.setBackground(new java.awt.Color(153, 153, 153));
        toGraphLabel.setForeground(new java.awt.Color(153, 153, 153));
        graphicPanel.setViewportView(toGraphLabel);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        identifiersPane.setBackground(new java.awt.Color(153, 153, 153));
        identifiersPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.IDNT_TKN.ordinal())
            , 0));
    jScrollPane1.setViewportView(identifiersPane);

    jTabbedPane1.addTab("Identifiers", jScrollPane1);

    decimalPane.setBackground(new java.awt.Color(153, 153, 153));
    decimalPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.DEC_TKN.ordinal())
        , 0));
jScrollPane2.setViewportView(decimalPane);

jTabbedPane1.addTab("Decimal", jScrollPane2);

integersPane.setBackground(new java.awt.Color(153, 153, 153));
integersPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.INT_TKN.ordinal())
    , 0));
    jScrollPane3.setViewportView(integersPane);

    jTabbedPane1.addTab("Integers", jScrollPane3);

    rsrvdWordsPane.setBackground(new java.awt.Color(153, 153, 153));
    rsrvdWordsPane.setLayout(new java.awt.GridLayout(tokenBag.groupSize(TokenTypes.RSRVDWRD_TKN.ordinal())
        , 0));
jScrollPane4.setViewportView(rsrvdWordsPane);

jTabbedPane1.addTab("ReservedWords", jScrollPane4);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(graphicPanel)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillPanels() {
        userInterfaceMagnament.setToGraphPanel(graphicPanel);
        userInterfaceMagnament.setToGrphLabel(toGraphLabel);
        userInterfaceMagnament.setJdialogParent(this);
        
        userInterfaceMagnament.tokenStacker(identifiersPane, tokenBag.groupTokens(TokenTypes.IDNT_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(integersPane, tokenBag.groupTokens(TokenTypes.INT_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(decimalPane, tokenBag.groupTokens(TokenTypes.DEC_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos
        userInterfaceMagnament.tokenStacker(rsrvdWordsPane, tokenBag.groupTokens(TokenTypes.RSRVDWRD_TKN.ordinal())); //agrupamos en forma de stack los tokens especificos

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel decimalPane;
    private javax.swing.JScrollPane graphicPanel;
    private javax.swing.JPanel identifiersPane;
    private javax.swing.JPanel integersPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel rsrvdWordsPane;
    private javax.swing.JLabel toGraphLabel;
    // End of variables declaration//GEN-END:variables
}
